# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: '1.2'
_src_path: https://github.com/m-birke/python-project-template.git
package_name: logging_extended_handlers
project_description: Extending logging.handlers
project_name: logging-extended-handlers
